{{- if .Values.useVault }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}-external-secret
spec:
  secretStoreRef:
    name: infra-secrets-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
  data:
    - secretKey: {{ .Values.secretKey }}
      remoteRef:
        key: {{ .Values.vaultSecretPath }}
        property: {{ .Values.secretKey }}
{{- end }}